### ISSUE TITLE
YIFY releases (not YTS) are not categorized as LQ (Radarr collection of custom formats)

### ISSUE THREAD

**Issue by sarpuser** [TRaSH-Guides/Guides#1288] opened 2023-04-27 03:51 UTC
Radarr collection of custom formats - LQ format:

Releases that have YIFY in the name are not categorized as LQ despite LQ having YIFY as one of its words. YTS works fine (it is categorized correctly). <br>
![Screenshot 2023-04-26 at 23 50 21](https://user-images.githubusercontent.com/23362324/234755002-1b3ad5dc-6cae-4cbd-b4a9-ec60eb133127.png) <br>
![Screenshot 2023-04-26 at 23 50 32](https://user-images.githubusercontent.com/23362324/234755020-0b8d685f-869e-4e89-bc46-48ac2e2fed67.png)

**Comment by bakerboy448** [comment] 2023-04-27 03:53
Not a bug `- Xxxxxx` has not release group
The standard is `-XXXXX` with some additional support for `XXXXXXX)` and `XXXXX]`

@TRaSH- should we split LQ into LQ Group & LQ Rls Name for groups that name sanely vs groups/terms to avoid?

**Comment by TRaSH-** [comment] 2023-04-27 06:38
So you mean like 2 LQ cf?

**Comment by bakerboy448** [comment] 2023-04-27 06:53
Yup

**Comment by TRaSH-** [comment] 2023-04-27 07:06
darn, that means we need to be very carefully what we add to that CF, because of some rlsgrp's have common words.
let's bring this in to discord, being it's easier. i will open a topic

**Comment by bakerboy448** [comment] 2023-07-03 18:41
how frequently is `- YIFY` encountered vs. `-YIFY` or `YIFY)`  seems like it's a renamed release and that's the root cause

**Comment by nuxencs** [comment] 2023-07-25 16:58
Fixed with https://github.com/Radarr/Radarr/pull/8883

**Comment by bakerboy448** [comment] 2023-08-19 02:16
https://github.com/Radarr/Radarr/compare/7f3e7b360bdb...d4fada9b4ec7

Fixed in radarr

**Closed by bakerboy448** 2023-08-19 02:16 UTC
Labels: Type: Enhancement, Area: Sonarr, Area: Radarr, Status: Waiting on Starr
